using System;
using System.Collections.Generic;
using System.Text;

namespace Java.Net.Flags
{
    [Flags]
    public enum AccessClass
    {
        NONE = 0x0000,
        PUBLIC = 0x0001, //Declared public; may be accessed from outside its package.
        PRIVATE = 0x0002,
        PROTECTED = 0x0004,
        STATIC = 0x0008,
        FINAL = 0x0010, //Declared final; no subclasses allowed.
        SUPER = 0x0020, //Treat superclass methods specially when invoked by the invokespecial instruction.
        INTERFACE = 0x0200, //Is an interface, not a class.
        ABSTRACT = 0x0400, //Declared abstract; must not be instantiated.
        SYNTHETIC = 0x1000, //Declared synthetic; not present in the source code.
        ANNOTATION = 0x2000, //Declared as an annotation type.
        ENUM = 0x4000, //Declared as an enum type.
    }
    [Flags]
    public enum AccessField
    {
        NONE = 0x0000,
        PUBLIC = 0x0001, //Declared public; may be accessed from outside its package.
        PRIVATE = 0x0002, //Declared private; usable only within the defining class.
        PROTECTED = 0x0004, //Declared protected; may be accessed within subclasses.
        STATIC = 0x0008, //Declared static.
        FINAL = 0x0010, //Declared final; never directly assigned to after object construction (JLS §17.5).
        VOLATILE = 0x0040, //Declared volatile; cannot be cached.
        TRANSIENT = 0x0080, //Declared transient; not written or read by a persistent object manager.
        SYNTHETIC = 0x1000, //Declared synthetic; not present in the source code.
        ENUM = 0x4000, //Declared as an element of an enum.
    }
    [Flags]
    public enum AccessMethod
    {
        NONE = 0x0000,
        PUBLIC = 0x0001, //Declared public; may be accessed from outside its package.
        PRIVATE = 0x0002, //Declared private; accessible only within the defining class.
        PROTECTED = 0x0004, //Declared protected; may be accessed within subclasses.
        STATIC = 0x0008, //Declared static.
        FINAL = 0x0010, //Declared final; must not be overridden (§5.4.5).
        SYNCHRONIZED = 0x0020, //Declared synchronized; invocation is wrapped by a monitor use.
        BRIDGE = 0x0040, //A bridge method, generated by the compiler.
        VARARGS = 0x0080, //Declared with variable number of arguments.
        NATIVE = 0x0100, //Declared native; implemented in a language other than Java.
        ABSTRACT = 0x0400, //Declared abstract; no implementation is provided.
        STRICT = 0x0800, //Declared strictfp; floating-point mode is FP-strict.
        SYNTHETIC = 0x1000, //Declared synthetic; not present in the source code.
    }
    [Flags]
    public enum AccessParameter
    {
        NONE = 0x0000,
        FINAL = 0x0010, //Indicates that the formal parameter was declared final
        SYNTHETIC = 0x1000, //Indicates that the formal parameter was not explicitly or implicitly declared in source code, according to the specification of the language in which the source code was written (JLS §13.1). (The formal parameter is an implementation artifact of the compiler which produced this class file.)
        MANDATED = 0x8000, //Indicates that the formal parameter was implicitly declared in source code, according to the specification of the language in which the source code was written (JLS §13.1). (The formal parameter is mandated by a language specification, so all compilers for the language must emit it.)
    }
    [Flags]
    public enum AccessProperty
    {
        NONE = 0x0000,
        PUBLIC = 0x0001, //Marked or implicitly public in source.
        PRIVATE = 0x0002, //Marked private in source.
        PROTECTED = 0x0004, //Marked protected in source.
        STATIC = 0x0008, //Marked or implicitly static in source.
        FINAL = 0x0010, //Marked final in source.
        INTERFACE = 0x0200, //Was an interface in source.
        ABSTRACT = 0x0400, //Marked or implicitly abstract in source.
        SYNTHETIC = 0x1000, //Declared synthetic; not present in the source code.
        ANNOTATION = 0x2000, //Declared as an annotation type.
        ENUM = 0x4000, //Declared as an enum type.
    }
}
